CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(255),
   price_per_sf FLOAT,
   sf_per_pc INTEGER,
   pcs_per_box INTEGER,
   price_per_box INTEGER,
   CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product ADD CONSTRAINT uc_product_title UNIQUE (title);